// SPDX-License-Identifier: Apache-2.0
import { useEffect, useState, type ComponentType } from 'react';
import {
  ArrowClockwise, ArrowsLeftRight, Blueprint, Broadcast, CheckCircle, Diamond,
  Files, Flask, GitMerge, Graph, IdentificationCard, Moon, PlugsConnected,
  SealCheck, ShieldCheck, SlidersHorizontal, SquaresFour, Sun, Tray,
} from '@phosphor-icons/react';
import { ApiState, loadState, request } from './api';
import { navigation as nav } from './navigation';

const labels: Record<string, [string, string]> = {
  overview: ['Operational overview', 'What needs attention across the mastering lane.'],
  models: ['Domain model studio', 'Versioned entities, attributes, identifiers, and operating modes.'],
  sources: ['Source connections', 'Capabilities are declared explicitly; ingestion is read-only by default.'],
  records: ['Source records & quarantine', 'Original contributions remain separate from enterprise identities.'],
  entities: ['Entity explorer', 'Approved records and candidates, with stable enterprise identities.'],
  master: ['Master record', 'The selected value, its source, and the rule that chose it.'],
  matches: ['Match workbench', 'A score is evidence—not proof. Hard contradictions win.'],
  survivorship: ['Survivorship editor', 'Attribute authority is evaluated independently at every change.'],
  inbox: ['Steward inbox', 'Version-bound work with durable decisions and separation of duties.'],
  corrections: ['Merge, split & repair', 'Local identity correction and downstream reconciliation are distinct.'],
  quality: ['Quality & profiling', 'Measured stored state, with scope and sample status disclosed.'],
  simulator: ['Configuration simulator', 'Impact previews bind policy version to a data checkpoint.'],
  operations: ['Publication center', 'At-least-once events with visible delivery and repair state.'],
  relationships: ['Relationship view', 'Typed, effective-dated links over persisted enterprise identities.'],
  access: ['Access, identities & audit', 'Roles shape every API read and action; audit is chained for ordinary roles.'],
};

const fmt = (value?: string) => value ? new Intl.DateTimeFormat('en', {month:'short', day:'numeric', hour:'2-digit', minute:'2-digit'}).format(new Date(value)) : '—';
const short = (value?: string) => value ? value.slice(0, 8) : '—';
const downloadJSON=(name:string,value:any)=>{const href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=href;link.download=name;link.click();URL.revokeObjectURL(href)};
const ruleLabel=(rule:any)=>typeof rule==='string'?rule:(rule?.strategy||'configured policy');

function Badge({children, tone='neutral'}:{children:any,tone?:string}) { return <span className={`badge ${tone}`}>{children}</span>; }
function Icon({name}:{name:string}) {
  const icons: Record<string, ComponentType<any>> = {
    overview: SquaresFour, models: Blueprint, sources: PlugsConnected, records: Files,
    entities: IdentificationCard, master: SealCheck, matches: ArrowsLeftRight,
    survivorship: SlidersHorizontal, inbox: Tray, corrections: GitMerge,
    quality: CheckCircle, simulator: Flask, operations: Broadcast,
    relationships: Graph, access: ShieldCheck,
  };
  const Glyph = icons[name] || SquaresFour;
  return <Glyph size={18} weight={name==='overview'?'fill':'regular'} aria-hidden="true"/>;
}

export function App() {
  const currentRoute=()=>{
    const candidate=location.hash.replace(/^#\/?/, '')||'overview';
    return nav.some(([route])=>route===candidate) ? candidate : 'overview';
  };
  const [page,setPage]=useState(currentRoute());
  const [role,setRole]=useState('administrator');
  const [theme,setTheme]=useState(localStorage.getItem('rl-theme')||'light');
  const [state,setState]=useState<ApiState|null>(null);
  const [error,setError]=useState('');
  const [loading,setLoading]=useState(true);
  const [refresh,setRefresh]=useState(0);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('rl-theme',theme)},[theme]);
  useEffect(()=>{const sync=()=>setPage(currentRoute());window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
  useEffect(()=>{setLoading(true);setError('');loadState(role).then(value=>{setState(value);setError('')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[role,refresh]);
  const go=(id:string)=>{setPage(id);location.hash=id};
  const reload=()=>setRefresh(x=>x+1);
  if(loading&&!state) return <div className="boot"><div className="mark">R</div><span>Preparing the mastering lane…</span></div>;
  const groups=[['Monitor',nav.slice(0,1)],['Model & ingest',nav.slice(1,4)],['Master data',nav.slice(4,8)],['Govern',nav.slice(8,12)],['Operate',nav.slice(12)]] as const;
  return <div className="shell">
    <a className="skip-link" href="#workspace-content">Skip to workspace</a>
    <aside>
      <div className="brand"><div className="mark">R</div><div><strong>recordlane</strong><small>Master data control</small></div></div>
      <nav aria-label="Product">{groups.map(([group,items])=><div className="nav-group" key={group}><span className="nav-label">{group}</span>{items.map(([id,label,index])=><button key={id} aria-label={label} aria-current={page===id?'page':undefined} className={page===id?'active':''} onClick={()=>go(id)}><Icon name={id}/><span>{label}</span><em>{index}</em></button>)}</div>)}</nav>
      <div className="identity"><div className="avatar">{role[0].toUpperCase()}</div><div><strong>{role.replace('_',' ')}</strong><small>Meridian Works</small></div><span className="online" title="Connected"/></div>
    </aside>
    <main id="workspace-content">
      <header><div className="eyebrow"><span>Meridian Works</span><i/>Synthetic workspace</div><div className="actions"><label className="role-select"><span>Viewing as</span><select aria-label="Demo role" value={role} onChange={e=>setRole(e.target.value)}>{['administrator','modeler','integration_operator','steward','approver','auditor','read_only'].map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select></label><button className="icon-button" aria-label={`Use ${theme==='dark'?'light':'dark'} theme`} title={`Use ${theme==='dark'?'light':'dark'} theme`} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><button className="icon-button" aria-label="Refresh workspace" title="Refresh workspace" onClick={reload}><ArrowClockwise size={17}/></button></div></header>
      <section className="title"><div><div className="kicker">Workspace / {nav.find(n=>n[0]===page)?.[2]}</div><h1>{labels[page]?.[0]}</h1><p>{labels[page]?.[1]}</p></div><div className="status"><span className="pulse"/><span><strong>Live workspace</strong>Updated just now</span></div></section>
      {error&&<div className="notice error"><strong>Could not load workspace</strong>{error}<button onClick={reload}>Retry</button></div>}
      {state&&<Page id={page} data={state} role={role} reload={reload}/>} 
      <footer><span>Recordlane 0.1.0-alpha.3</span><span>Loopback demo · external AI off</span><span>At-least-once publication</span></footer>
    </main>
  </div>;
}

function Page({id,data,role,reload}:{id:string,data:ApiState,role:string,reload:()=>void}) {
  const first=data.entities.find(e=>e.master&&e.approval_state==='approved')||data.entities.find(e=>e.master);
  if(id==='overview') return <Overview d={data}/>;
  if(id==='models') return <Models d={data} role={role} reload={reload}/>;
  if(id==='sources') return <Sources d={data} role={role} reload={reload}/>;
  if(id==='records') return <Records d={data}/>;
  if(id==='entities') return <Entities d={data}/>;
  if(id==='master') return <Master entity={first}/>;
  if(id==='matches') return <Matches d={data} role={role} reload={reload}/>;
  if(id==='survivorship') return <Survivorship entity={first}/>;
  if(id==='inbox') return <Inbox d={data} role={role} reload={reload}/>;
  if(id==='corrections') return <Corrections d={data} role={role} reload={reload}/>;
  if(id==='quality') return <Quality d={data} role={role}/>;
  if(id==='simulator') return <Simulator d={data} role={role} reload={reload}/>;
  if(id==='operations') return <Operations d={data} role={role} reload={reload}/>;
  if(id==='relationships') return <Relationships d={data} role={role} reload={reload}/>;
  return <Access d={data} role={role} reload={reload}/>;
}

function Overview({d}:{d:ApiState}) {const c=d.overview.counts;return <>
  <div className="metric-grid"><Metric value={c.source_records} label="Source contributions" note="Across 3 local sources"/><Metric value={c.open_reviews} label="Open decisions" note="Version-bound queue" tone="amber"/><Metric value={c.quarantined} label="Quality exceptions" note="Preserved for repair" tone="red"/><Metric value={c.outbox_pending} label="Pending deliveries" note="Consumer reconciliation" tone="blue"/></div>
  <div className="grid two"><Panel title="Attention lane" aside="Ordered by consequence"><div className="attention"><Attention tone="red" n={c.quarantined} title="Record held in quarantine" text="Invalid jurisdiction, identifier, and lifecycle values."/><Attention tone="amber" n={d.tasks.filter(t=>t.kind==='duplicate_match'&&t.status==='open').length} title="Identity decisions waiting" text="Similarity evidence requires steward judgment."/><Attention tone="blue" n={c.outbox_pending} title="Approved changes awaiting relay" text="No downstream consistency is implied until reconciled."/></div></Panel><Panel title="Source freshness" aside="Measured from persisted checkpoints"><table><thead><tr><th>Source</th><th>Mode</th><th>Last observed</th><th>State</th></tr></thead><tbody>{d.sources.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{s.kind}</td><td>{fmt(s.last_ingested_at)}</td><td><Badge tone="good">{s.status}</Badge></td></tr>)}</tbody></table></Panel></div>
  <Panel title="Mastering flow" aside="Current workspace"><div className="flow"><Flow n="01" title="Collect" text={`${c.source_records} source records`}/><Flow n="02" title="Resolve" text={`${d.entities.length} stable identities`}/><Flow n="03" title="Govern" text={`${c.open_reviews} open decisions`}/><Flow n="04" title="Publish" text={`${c.mastered_entities} approved masters`}/></div></Panel>
  </>}
function Metric({value,label,note,tone='lime'}:{value:any,label:string,note:string,tone?:string}){return <div className={`metric ${tone}`}><div className="metric-top"><span>{label}</span><i/></div><strong>{String(value).padStart(2,'0')}</strong><small>{note}</small></div>}
function Attention({tone,n,title,text}:{tone:string,n:number,title:string,text:string}){return <div className="attention-row"><span className={`count ${tone}`}>{n}</span><div><strong>{title}</strong><p>{text}</p></div><span>→</span></div>}
function Flow({n,title,text}:{n:string,title:string,text:string}){return <div className="flow-step"><em>{n}</em><strong>{title}</strong><span>{text}</span></div>}

function Models({d,role,reload}:{d:ApiState,role:string,reload:()=>void}) {
  const [selectedId,setSelectedId]=useState(d.domains[0]?.id||'');
  const selected=d.domains.find(x=>x.id===selectedId)||d.domains[0];
  const [editor,setEditor]=useState(JSON.stringify(selected?.definition||{},null,2));
  const [targetSlug,setTargetSlug]=useState('new-workspace');
  const [targetName,setTargetName]=useState('New workspace');
  const [domainKey,setDomainKey]=useState('asset');
  const [domainName,setDomainName]=useState('Asset');
  const [identifier,setIdentifier]=useState('serial_number');
  const [msg,setMsg]=useState('');
  useEffect(()=>setEditor(JSON.stringify(selected?.definition||{},null,2)),[selected?.id]);
  const save=async()=>{try{const definition=JSON.parse(editor);await request('/configurations',role,{method:'POST',body:JSON.stringify({document:{domains:{[selected.key]:definition}}})});setMsg('Validated configuration draft created');reload()}catch(e:any){setMsg(e.message)}};
  const exportBundle=async()=>{try{const bundle=await request('/workspace-bundle',role);downloadJSON('recordlane-workspace-bundle.json',bundle);setMsg('Portable workspace bundle exported')}catch(e:any){setMsg(e.message)}};
  const revert=async(id:string)=>{try{const created=await request(`/configurations/${id}/revert`,role,{method:'POST'});setMsg(`Revert draft v${created.version} created; simulation and approval are still required`);reload()}catch(e:any){setMsg(e.message)}};
  const importBundle=async(file:File,target?:string)=>{try{const bundle=JSON.parse(await file.text());if(target){await request('/workspaces',role,{method:'POST',body:JSON.stringify({slug:target,name:targetName})});await request('/workspace-bundle/import',role,{method:'POST',body:JSON.stringify({bundle,target_workspace:target})})}else await request('/workspace-bundle/import',role,{method:'POST',body:JSON.stringify({bundle})});setMsg(target?`Bundle imported into ${target}`:'Bundle imported into this workspace');reload()}catch(e:any){setMsg(e.message)}};
  const createDomain=async()=>{try{const definition={entity:domainKey,mode:'registry',policy_version:'1.0',attributes:[{key:'name',name:`${domainName} name`,type:'string',required:true,normalizer:'unicode_casefold'},{key:identifier,name:identifier.replaceAll('_',' '),type:'identifier',required:true,normalizer:'uppercase_trim'}],identifiers:[{field:identifier,namespace:`${domainKey}:${identifier}`,hard_conflict:true}],matching:{blocking:[{fields:[identifier]}],comparisons:[{field:identifier,comparator:'exact',weight:1}],thresholds:{review:0.8,auto_link:1}},survivorship:{default:'verified_then_source_priority_then_observation_time'},relationships:[]};await request('/domains',role,{method:'POST',body:JSON.stringify({key:domainKey,name:domainName,mode:'registry',definition})});setMsg(`${domainName} domain and ${identifier} rule validated and persisted`);reload()}catch(e:any){setMsg(e.message)}};
  return <div className="grid sidebar-grid"><Panel title="Domains" aside={`${d.domains.length} published`}><div className="domain-list">{d.domains.map(x=><button className={`list-row ${selected?.id===x.id?'selected':''}`} onClick={()=>setSelectedId(x.id)} key={x.id}><div className="square">{x.name[0]}</div><div><strong>{x.name}</strong><small>{x.mode} · v{x.schema_version}</small></div><Badge tone="good">{x.status}</Badge></button>)}</div><div className="config-history"><small>Create governed domain</small><div className="form-stack"><input aria-label="Domain key" value={domainKey} onChange={e=>setDomainKey(e.target.value)}/><input aria-label="Domain name" value={domainName} onChange={e=>setDomainName(e.target.value)}/><input aria-label="Identifier attribute" value={identifier} onChange={e=>setIdentifier(e.target.value)}/><button className="primary" onClick={createDomain}>Create domain & rule</button></div><small>Configuration history</small>{d.configs.slice(0,3).map(c=><div className="config-row" key={c.id}><span><strong>v{c.version}</strong> · {c.status}</span><button onClick={()=>revert(c.id)}>Create revert draft</button></div>)}</div><div className="bundle-actions"><button onClick={exportBundle}>Export workspace bundle</button><label className="file-button">Import here<input type="file" accept="application/json,.json" onChange={e=>e.target.files?.[0]&&importBundle(e.target.files[0])}/></label><div className="form-grid"><input aria-label="Target workspace slug" value={targetSlug} onChange={e=>setTargetSlug(e.target.value)}/><input aria-label="Target workspace name" value={targetName} onChange={e=>setTargetName(e.target.value)}/><label className="file-button primary">Create target & import<input type="file" accept="application/json,.json" onChange={e=>e.target.files?.[0]&&importBundle(e.target.files[0],targetSlug)}/></label></div></div>{msg&&<div className="inline-message">{msg}</div>}</Panel><Panel title={selected?.name||'Domain'} aside="Validated policy editor"><div className="model-head"><div><Badge tone="purple">{selected?.mode}</Badge><h2>{selected?.definition?.entity}</h2><p>Edit the executable policy as JSON. Unsupported settings are rejected by the same compiler used for ingestion and simulation.</p></div><button onClick={()=>downloadJSON(`${selected?.key||'domain'}-policy.json`,selected?.definition)}>Export policy</button></div><textarea className="policy-editor" aria-label="Domain policy JSON" value={editor} onChange={e=>setEditor(e.target.value)} spellCheck={false}/><div className="decision-bar"><button className="primary" onClick={save}>Create validated draft</button></div></Panel></div>
}

function Sources({d,role,reload}:{d:ApiState,role:string,reload:()=>void}) {
  const [key,setKey]=useState('new-source');const [name,setName]=useState('New source');const [kind,setKind]=useState('rest');const [location,setLocation]=useState('https://source.example/api');const [msg,setMsg]=useState('');const [checking,setChecking]=useState('');
  const defaults:Record<string,string>={postgresql:'env:RECORDLANE_SOURCE_DSN',rest:'https://source.example/api',odata:'https://source.example/odata',webhook:'file:/run/recordlane/inbound-webhook',csv:'/data/source.csv',jsonl:'/data/source.jsonl',parquet:'/data/source.parquet',s3:'https://bucket.example/object',azure_blob:'https://account.blob.core.windows.net/container/object',gcs:'https://storage.googleapis.com/bucket/object'};
  const create=async()=>{try{const host=location.startsWith('http')?new URL(location).hostname:'';const config=kind==='postgresql'?{secret_ref:location}:kind==='rest'?{base_url:location,allowed_hosts:[host],pagination:'cursor'}:kind==='odata'?{base_url:location,allowed_hosts:[host],entity_set:'Suppliers',delta:true}:kind==='webhook'?{secret_ref:location,format:'debezium-1.0',id_field:'id'}:['s3','azure_blob','gcs'].includes(kind)?{object_url:location,allowed_hosts:[host]}:{path:location,encoding:'utf-8'};await request('/sources',role,{method:'POST',body:JSON.stringify({key,name,kind,priority:100,capabilities:{direction:['read'],full_read:kind!=='webhook',deletions:'explicit'},config})});setMsg('Source definition validated and persisted');reload()}catch(e:any){setMsg(e.message)}};
  const testConnection=async(source:any)=>{setChecking(source.key);try{const result=await request(`/sources/${source.key}/test`,role,{method:'POST'});setMsg(`${source.name} connection verified over ${result.protocol}`);reload()}catch(e:any){setMsg(e.message)}finally{setChecking('')}};
  return <><div className="source-grid">{d.sources.map((s,i)=><div className="source-card" key={s.id}><div className="source-num">{String(i+1).padStart(2,'0')}</div><Badge tone={s.status==='healthy'?'good':s.status==='error'?'red':'neutral'}>{s.status}</Badge><h3>{s.name}</h3><p>{s.kind.replaceAll('_',' ').toUpperCase()} · priority {s.priority}</p><dl><dt>Full read</dt><dd>{String(s.capabilities.full_read)}</dd><dt>Incremental</dt><dd>{s.capabilities.incremental||'—'}</dd><dt>Deletion</dt><dd>{s.capabilities.deletions}</dd><dt>Credential</dt><dd>{s.config?.secret_ref||'not stored inline'}</dd></dl><div className="source-actions"><button disabled={checking===s.key} onClick={()=>testConnection(s)}>{checking===s.key?'Checking…':'Test connection'}</button></div><div className="card-footnote">The backend opens the configured boundary; values and credentials are never returned.</div></div>)}</div><Panel title="Add source" aside="Validated configuration"><div className="form-grid source-form"><input aria-label="Source key" value={key} onChange={e=>setKey(e.target.value)}/><input aria-label="Source name" value={name} onChange={e=>setName(e.target.value)}/><select aria-label="Source kind" value={kind} onChange={e=>{setKind(e.target.value);setLocation(defaults[e.target.value])}}><option value="rest">REST API</option><option value="odata">OData</option><option value="postgresql">PostgreSQL</option><option value="webhook">Signed webhook / Debezium</option><option value="csv">CSV</option><option value="jsonl">JSONL</option><option value="parquet">Parquet</option><option value="s3">S3-compatible object</option><option value="azure_blob">Azure Blob object</option><option value="gcs">Google Cloud Storage object</option></select><input aria-label="Source location or secret reference" value={location} onChange={e=>setLocation(e.target.value)}/><button className="primary" onClick={create}>Save source</button></div>{msg&&<div className="inline-message">{msg}</div>}</Panel><div className="notice"><strong>Capability honesty</strong>Local SQL, HTTP, files, events, and the demo consumer are executed locally. Cloud object adapters remain contract-tested until vendor credentials are supplied.</div></>
}

function Records({d}:{d:ApiState}){const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');const rows=d.records.filter(r=>(filter==='all'||r.state===filter)&&JSON.stringify(r.original).toLowerCase().includes(query.toLowerCase()));return <Panel title="Contribution ledger" aside={`${rows.length} of ${d.records.length} records`}><div className="toolbar"><div className="segmented">{['all','valid','quarantine'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter name or value" aria-label="Filter records"/></div><table><thead><tr><th>Source key</th><th>Original name</th><th>Identifier</th><th>Observed</th><th>State</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><code>{r.local_id}</code><small>v{r.source_version}</small></td><td><strong dir="auto">{r.original.name}</strong>{r.quality_errors?.[0]&&<small className="danger">{r.quality_errors[0].message}</small>}</td><td>{r.original.tax_id||'—'}</td><td>{fmt(r.observed_at)}</td><td><Badge tone={r.state==='valid'?'good':'red'}>{r.state}</Badge></td></tr>)}</tbody></table></Panel>}

function Entities({d}:{d:ApiState}){const [query,setQuery]=useState('');const rows=d.entities.filter(e=>JSON.stringify(e.master?.values||{}).toLowerCase().includes(query.toLowerCase())||e.stable_key.includes(query));return <Panel title="Enterprise identities" aside={`${rows.length} visible · candidates labeled`}><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search approved values" aria-label="Search entities"/><button onClick={()=>downloadJSON('recordlane-entities.json',rows)}>Export visible</button></div><table><thead><tr><th>Stable identity</th><th>Selected name</th><th>Jurisdiction</th><th>Version</th><th>State</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td><code>{e.stable_key}</code></td><td><strong dir="auto">{e.master?.values?.name||'Awaiting master'}</strong></td><td>{e.master?.values?.country||'—'}</td><td>v{e.master?.version||e.version}</td><td><Badge tone={e.approval_state==='approved'?'good':'amber'}>{e.approval_state}</Badge></td></tr>)}</tbody></table></Panel>}

function Master({entity}:{entity:any}){const values=entity?.master?.values||{},prov=entity?.master?.provenance||{};return <div className="grid master-grid"><Panel title={values.name||'No selected entity'} aside={entity?.stable_key}><div className="record-hero"><div className="monogram">{values.name?.[0]||'R'}</div><div><Badge tone={entity?.approval_state==='approved'?'good':'amber'}>{entity?.approval_state}</Badge><h2 dir="auto">{values.name}</h2><p>{values.country} · {values.tax_id}</p></div></div><div className="attribute-list">{Object.entries(values).map(([k,v])=><div className="attribute" key={k}><span>{k.replace('_',' ')}</span><strong dir="auto">{String(v)}</strong><small>{prov[k]?.source||'Source pending'} · {prov[k]?.verification||'unverified'}</small></div>)}</div></Panel><Panel title="Selection explanation" aside={`Master v${entity?.master?.version||'—'}`}>{Object.entries(prov).map(([k,p]:any)=><div className="provenance" key={k}><div className="line-dot"/><div><strong>{k.replace('_',' ')}</strong><p>Selected from <b>{p.source}</b> by {ruleLabel(p.rule).replaceAll('_',' ')}.</p><div><Badge tone={p.verification==='verified'?'good':'neutral'}>{p.verification}</Badge><code>source v{p.source_version}</code><span>{p.alternatives} competing</span></div></div></div>)}</Panel></div>}

function Matches({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const task=d.tasks.find(t=>t.kind==='duplicate_match'&&t.status==='open');const [message,setMessage]=useState('');const act=async(decision:string)=>{if(!task)return;try{await request(`/review-tasks/${task.id}/decision`,role,{method:'POST',body:JSON.stringify({decision,reason:decision==='link'?'Evidence reviewed; records represent one supplier':'Identifiers remain ambiguous; keep separate'})});setMessage('Decision persisted');reload()}catch(e:any){setMessage(e.message)}};if(!task)return <Empty title="No match reviews are open" text="New ambiguous evidence will enter this workbench."/>;const p=task.payload;const probabilistic=p.score_kind==='estimated_match_probability';return <div className="grid match-grid"><Panel title="Candidate pair" aside={`Policy ${p.policy_version}`}><div className="score"><strong>{Math.round(p.score*100)}</strong><span>/ 100 {probabilistic?'estimated match probability':'weighted score'}</span><Badge tone="amber">human review</Badge></div><div className="compare"><div><small>NEW CONTRIBUTION</small><h3>{short(p.left_record_id)}</h3></div><div className="versus">↔</div><div><small>EXISTING CONTRIBUTION</small><h3>{short(p.right_record_id)}</h3></div></div><div className="decision-bar"><button onClick={()=>act('keep_separate')}>Keep separate</button><button className="primary" onClick={()=>act('link')}>Link identities</button></div>{message&&<div className="inline-message">{message}</div>}</Panel><Panel title="Evidence ledger" aside={probabilistic?'Fellegi–Sunter parameters':'Not a calibrated probability'}>{p.evidence.map((e:any)=><div className="evidence" key={e.field}><div><strong>{e.field}</strong><small>{e.comparator} · {probabilistic?`log LR ${e.log_likelihood_ratio}`:`weight ${e.weight}`}</small></div><div className="bar"><i style={{width:`${e.score*100}%`}}/></div><b>{Math.round(e.score*100)}</b></div>)}{p.contradictions?.length?<div className="notice error">Hard contradiction prevents linking.</div>:<div className="notice"><strong>No hard contradiction</strong>Similarity still requires stewardship at this threshold.</div>}</Panel></div>}

function Survivorship({entity}:{entity:any}){const p=entity?.master?.provenance||{};return <Panel title="Attribute authority" aside="Deterministic tie-breaking"><table><thead><tr><th>Attribute</th><th>Current authority</th><th>Verification</th><th>Fallbacks</th><th>Re-evaluation</th></tr></thead><tbody>{Object.entries(p).map(([k,v]:any)=><tr key={k}><td><strong>{k.replace('_',' ')}</strong></td><td>{v.source}</td><td><Badge tone={v.verification==='verified'?'good':'neutral'}>{v.verification}</Badge></td><td>{v.alternatives}</td><td>On contribution or policy change</td></tr>)}</tbody></table><div className="notice"><strong>Sensitive identifier guard</strong>A newer unverified spreadsheet value cannot replace a verified legal identifier under this policy.</div></Panel>}

function TaskEvidence({task,d}:{task:any,d:ApiState}) {
  const entity=d.entities.find(e=>e.id===task.entity_id);
  const evidence=task.payload.values||task.payload.impact||task.payload.evidence||{};
  const entries=Array.isArray(evidence)?evidence.map((value,index)=>[String(index+1),value]):Object.entries(evidence);
  return <div className="task-evidence"><div className="decision-facts"><div><small>Identity</small><strong>{entity?.master?.values?.name||entity?.stable_key||'Configuration scope'}</strong></div><div><small>Proposed by</small><strong>{task.proposed_by||'governed workflow'}</strong></div><div><small>Due</small><strong>{fmt(task.due_at)}</strong></div></div>{entries.length?<div className="evidence-values">{entries.map(([key,value]:any)=><div key={key}><span>{key.replaceAll('_',' ')}</span><strong dir="auto">{typeof value==='object'?JSON.stringify(value):String(value)}</strong></div>)}</div>:<div className="notice"><strong>No attribute values change in this item</strong>The decision still records the exact entity and workflow versions, actor, reason, audit entry, and publication consequence.</div>}</div>
}

function Inbox({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const [msg,setMsg]=useState('');const [selected,setSelected]=useState('');const open=d.tasks.filter(t=>t.status==='open');const active=open.find(t=>t.id===selected)||open[0];const decide=async(t:any,decision:'approve'|'reject')=>{try{await request(`/review-tasks/${t.id}/decision`,role,{method:'POST',body:JSON.stringify({decision,reason:decision==='approve'?'Reviewed exact version and supporting provenance':'Evidence does not support this proposed change'})});setMsg(decision==='approve'?'Approval committed with its publication event':'Decision rejected and recorded');reload()}catch(e:any){setMsg(e.message)}};return <div className="grid sidebar-grid"><Panel title="Queue" aside={`${open.length} open`}>{open.map(t=><button className={`task-row ${active?.id===t.id?'selected':''}`} onClick={()=>setSelected(t.id)} key={t.id}><span className={`task-kind ${t.priority}`}/><div><strong>{t.kind.replaceAll('_',' ')}</strong><small>{t.sensitive?'Sensitive · independent approval':'Standard review'} · due {fmt(t.due_at)}</small></div><code>{short(t.id)}</code></button>)}</Panel><Panel title="Decision detail" aside="Bound to exact version">{active?<><div className="decision-summary"><Badge tone={active.sensitive?'red':'neutral'}>{active.sensitive?'sensitive':'standard'}</Badge><h2>{active.kind.replaceAll('_',' ')}</h2><p>Entity version {active.bound_entity_version??'—'} · workflow version {active.workflow_version}</p></div><TaskEvidence task={active} d={d}/><div className="decision-bar"><button onClick={()=>decide(active,'reject')}>Reject</button><button className="primary" onClick={()=>decide(active,'approve')}>Approve exact version</button></div>{msg&&<div className="inline-message">{msg}</div>}</>:<Empty title="Queue cleared" text="There is no open item for this filter."/>}</Panel></div>}

function Corrections({d,role,reload}:{d:ApiState,role:string,reload:()=>void}) {
  const candidates=d.entities.filter(e=>e.status!=='merged');const pair=candidates.slice(0,2);const splittable=candidates.filter(e=>e.current_contribution_count>0);const [preview,setPreview]=useState<any>(null);const [msg,setMsg]=useState('');const [entityId,setEntityId]=useState(splittable[0]?.id||'');const [detail,setDetail]=useState<any>(null);const [recordId,setRecordId]=useState('');
  useEffect(()=>{if(!entityId)return;request(`/entities/${entityId}`,role).then(value=>{setDetail(value);setRecordId(value.contributions?.[0]?.id||'')}).catch(e=>setMsg(e.message))},[entityId,role,d.entities.length]);
  const run=async(commit=false)=>{setMsg('');try{const result=await request(commit?'/merges':'/merges/preview',role,{method:'POST',body:JSON.stringify({entity_ids:pair.map(e=>e.id),reason:'Operator-reviewed duplicate correction'})});if(commit){setMsg(`Merge proposal ${short(result.review_task_id)} opened for independent approval`);reload()}else setPreview(result)}catch(e:any){setMsg(e.message)}};
  const split=async()=>{try{const result=await request(`/entities/${entityId}/splits`,role,{method:'POST',body:JSON.stringify({source_record_ids:[recordId],reason:'Operator-reviewed evidence assigns this contribution to a distinct identity'})});setMsg(`Split proposal ${short(result.id)} opened for independent approval`);reload()}catch(e:any){setMsg(e.message)}};
  return <><div className="metric-grid three"><Metric value={d.entities.filter(e=>e.status==='merged').length} label="Merged aliases" note="Stable references preserved"/><Metric value={d.tasks.filter(t=>['merge_approval','split_approval'].includes(t.kind)&&t.status==='open').length} label="Ambiguous repairs" note="Require operator judgment" tone="amber"/><Metric value={d.overview.counts.outbox_pending} label="Consumer checks" note="Not called rolled back" tone="blue"/></div><div className="grid two"><Panel title="Merge identities" aside="Preview before proposal">{pair.length===2?<><div className="compare"><div><small>PRIMARY CANDIDATE</small><h3>{pair[0].master?.values?.name||pair[0].stable_key}</h3><code>{pair[0].stable_key}</code></div><div className="versus">+</div><div><small>ALIAS CANDIDATE</small><h3>{pair[1].master?.values?.name||pair[1].stable_key}</h3><code>{pair[1].stable_key}</code></div></div>{preview&&<div className="impact"><div><strong>{preview.source_contributions}</strong><span>current contributions</span></div><div><strong>{preview.relationships}</strong><span>relationships affected</span></div></div>}<div className="decision-bar"><button onClick={()=>run(false)}>Preview impact</button><button className="primary" onClick={()=>run(true)}>Propose merge</button></div></>:<Empty title="No correction candidates" text="At least two identities are required for a governed preview."/>}</Panel><Panel title="Split contribution" aside="Exact membership version"><div className="form-stack"><label>Enterprise identity<select aria-label="Identity to split" value={entityId} onChange={e=>setEntityId(e.target.value)}>{splittable.map(e=><option value={e.id} key={e.id}>{e.master?.values?.name||e.stable_key}</option>)}</select></label><label>Source contribution<select aria-label="Contribution to split" value={recordId} onChange={e=>setRecordId(e.target.value)}>{detail?.contributions?.map((r:any)=><option value={r.id} key={r.id}>{r.local_id} · {r.original?.name||r.id}</option>)}</select></label><button className="primary" disabled={!recordId} onClick={split}>Propose split</button></div><div className="notice"><strong>Independent approval</strong>The contribution moves only after an approver accepts the exact bound entity version.</div></Panel></div>{msg&&<div className="inline-message">{msg}</div>}</>
}

function Quality({d,role}:{d:ApiState,role:string}) {
  const bad=d.records.filter(r=>r.state==='quarantine');
  const profile=d.quality;
  const identifier=profile.fields.find((field:any)=>field.field==='tax_id')||profile.fields.find((field:any)=>field.unique>0);
  const scope=profile.scope==='full_population'?'Full population':`Bounded sample of ${profile.sample_size}`;
  const [assistant,setAssistant]=useState<any>(null);
  const [assistantError,setAssistantError]=useState('');
  const explain=async()=>{
    setAssistantError('');
    try {
      setAssistant(await request('/assistant/drafts',role,{method:'POST',body:JSON.stringify({purpose:'explain_quality',domain:'supplier',objective:'Explain the measured quality failures and recommend governed recovery steps.',evidence_refs:['quality:supplier']})}));
    } catch(e:any) { setAssistantError(e.message); }
  };
  return <>
    <div className="metric-grid three"><Metric value={`${Math.round(100*profile.required_completeness)}%`} label="Required completeness" note={`${scope} · n=${profile.population}`}/><Metric value={identifier?.unique||0} label="Unique identifiers" note={identifier?`${identifier.field} · authorized values only`:'No readable identifier'} tone="blue"/><Metric value={profile.invalid_records} label="Invalid records" note={`Measured ${fmt(profile.measured_at)}`} tone="red"/></div>
    <div className="grid two quality-grid">
      <Panel title="Field profile" aside={`${scope} · current observations`}><table><thead><tr><th>Field</th><th>Complete</th><th>Missing</th><th>Unique</th><th>Identity conflicts</th></tr></thead><tbody>{profile.fields.map((field:any)=><tr key={field.field}><td><strong>{field.field}</strong>{field.required&&<Badge tone="amber">required</Badge>}</td><td>{Math.round(100*field.completeness)}%</td><td>{field.missing}</td><td>{field.unique}</td><td>{field.conflicting_entities}</td></tr>)}</tbody></table></Panel>
      <Panel title="Governed assistant" aside="Local provider · no external egress"><div className="assistant-intro"><Badge tone="purple">review only</Badge><h3>Explain this measured profile</h3><p>The assistant receives only fields this role can read. It has no tools, cannot approve work, and records an evidence digest instead of the prompt.</p><button className="primary" onClick={explain}>Explain profile</button></div>{assistant&&<div className="assistant-result"><strong>{assistant.result.summary}</strong><ul>{assistant.result.recommendations.map((item:string)=><li key={item}>{item}</li>)}</ul><small>{assistant.result.limitations.join(' ')}</small></div>}{assistantError&&<div className="inline-message">{assistantError}</div>}</Panel>
    </div>
    <Panel title="Actionable exceptions" aside={`Visible API page · n=${d.records.length}`}><table><thead><tr><th>Record</th><th>Field</th><th>Rule</th><th>Recovery</th></tr></thead><tbody>{bad.flatMap(r=>r.quality_errors.map((e:any)=><tr key={`${r.id}-${e.attribute}`}><td><code>{r.local_id}</code></td><td>{e.attribute}</td><td><Badge tone="red">{e.code}</Badge> {e.message}</td><td>Repair source value, then reprocess</td></tr>))}</tbody></table></Panel>
  </>;
}

function Simulator({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const draft=d.configs.find(c=>c.status==='draft');const s=d.simulations.find(x=>x.config_id===draft?.id);const [msg,setMsg]=useState('');const run=async()=>{try{await request(`/configurations/${draft.id}/simulate`,role,{method:'POST'});setMsg('Side-effect-free simulation persisted against the current snapshot');reload()}catch(e:any){setMsg(e.message)}};const propose=async()=>{try{await request(`/configurations/${draft.id}/propose`,role,{method:'POST',body:JSON.stringify({simulation_id:s.id})});setMsg('Activation proposal opened for independent approval');reload()}catch(e:any){setMsg(e.message)}};const metrics=s?[['candidate_links_changed',s.result.candidate_links_changed],['mastered_attributes_changed',s.result.mastered_attributes_changed],['validation_failures_changed',s.result.validation_failures_changed],['review_workload_delta',s.result.review_workload_delta]]:[];return <div className="grid two"><Panel title="Policy diff" aside={draft?`Draft v${draft.version}`:'No draft'}><div className="diff"><span>- current approved policy</span><span>+ content-addressed draft {short(draft?.checksum)}</span><span>+ exact record-level impact evidence</span></div><div className="decision-bar"><button onClick={run} disabled={!draft}>Recompute impact</button><button className="primary" onClick={propose} disabled={!draft||!s||s.stale}>Propose activation</button></div>{msg&&<div className="inline-message">{msg}</div>}</Panel><Panel title="Measured impact" aside={s?.result.sample?'Sampled run':`Full snapshot · n=${s?.result.details?.reduce((n:number,x:any)=>n+x.dataset_size,0)||0}`} >{s&&<div className="impact">{metrics.map(([k,v])=><div key={String(k)}><strong>{String(v).padStart(2,'0')}</strong><span>{String(k).replaceAll('_',' ')}</span></div>)}</div>}<div className={`notice ${s?.stale?'error':''}`}><strong>{s?.stale?'Preview expired':'Preview is current'}</strong>{s?.stale?'A material dependency changed; recompute before approval.':'Policy, source, membership, constraint, and entity revisions still match.'}</div></Panel></div>}

function Operations({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const [msg,setMsg]=useState('');const operate=async(path:string)=>{try{const result=await request(path,role,{method:'POST'});setMsg(path.endsWith('reconcile')?`${result.verified} verified, ${result.absent} returned to retry, ${result.unresolved} unresolved`:`${result.delivered} delivered, ${result.ambiguous} awaiting reconciliation, ${result.failed} failed`);reload()}catch(e:any){setMsg(e.message)}};return <div className="grid two"><Panel title="Transactional outbox" aside={d.operations.delivery_semantics}><div className="toolbar"><button className="primary" onClick={()=>operate('/operations/relay')}>Relay pending events</button><button onClick={()=>operate('/operations/reconcile')}>Reconcile ambiguous</button></div><table><thead><tr><th>Event</th><th>Entity / version</th><th>Attempts</th><th>Delivery</th></tr></thead><tbody>{d.operations.outbox.map((e:any)=><tr key={e.id}><td><strong>{e.event_type}</strong><code>{short(e.id)}</code></td><td>{short(e.entity_id)} · v{e.entity_version}</td><td>{e.attempts}</td><td><Badge tone={e.status==='delivered'?'good':'amber'}>{e.status}</Badge></td></tr>)}</tbody></table>{msg&&<div className="inline-message">{msg}</div>}<div className="notice"><strong>Ordering and consistency</strong>Ordering is per entity. Ambiguous writes are checked against the consumer receipt before retry.</div></Panel><Panel title="Durable work" aside={`${d.operations.jobs?.length||0} jobs`}>{d.operations.jobs?.length?<table><thead><tr><th>Kind</th><th>Attempts</th><th>State</th></tr></thead><tbody>{d.operations.jobs.map((job:any)=><tr key={job.id}><td><strong>{job.kind.replaceAll('_',' ')}</strong><code>{short(job.id)}</code></td><td>{job.attempts}</td><td><Badge tone={job.status==='complete'?'good':'amber'}>{job.status}</Badge></td></tr>)}</tbody></table>:<Empty title="No queued work" text="Policy activation and recovery operations will appear here."/>}</Panel></div>}

function Relationships({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const nodes=d.entities.slice(0,4);const [from,setFrom]=useState(nodes[0]?.id||'');const [to,setTo]=useState(nodes[1]?.id||'');const [type,setType]=useState('supplies');const [msg,setMsg]=useState('');const create=async()=>{try{await request('/relationships',role,{method:'POST',body:JSON.stringify({from_entity_id:from,to_entity_id:to,type})});setMsg('Governed relationship persisted with actor provenance');reload()}catch(e:any){setMsg(e.message)}};return <div className="grid two"><Panel title="Identity graph" aside="Persisted nodes only"><div className="graph" role="img" aria-label="Table-equivalent relationship view"><svg viewBox="0 0 600 340">{d.relationships.slice(0,4).map((r:any,i:number)=><line key={r.id} x1={i%2?440:150} y1={i%2?170:100} x2={i%2?460:190} y2={i%2?285:270}/>)}{nodes.map((n,i)=>{const pos=[[150,100],[440,170],[190,270],[460,285]][i];return <g key={n.id} transform={`translate(${pos[0]},${pos[1]})`}><circle r="44"/><text textAnchor="middle" y="5">{n.master?.values?.name?.slice(0,10)||short(n.id)}</text></g>})}</svg></div></Panel><Panel title="Governed relationship" aside={`${d.relationships.length} effective links`}><div className="form-stack"><label>From identity<select value={from} onChange={e=>setFrom(e.target.value)}>{nodes.map(n=><option key={n.id} value={n.id}>{n.master?.values?.name||n.stable_key}</option>)}</select></label><label>Relationship<input value={type} onChange={e=>setType(e.target.value)} aria-label="Relationship type"/></label><label>To identity<select value={to} onChange={e=>setTo(e.target.value)}>{nodes.map(n=><option key={n.id} value={n.id}>{n.master?.values?.name||n.stable_key}</option>)}</select></label><button className="primary" onClick={create}>Create relationship</button></div>{msg&&<div className="inline-message">{msg}</div>}{d.relationships.length?<table><tbody>{d.relationships.map(r=><tr key={r.id}><td>{short(r.from_entity_id)}</td><td>{r.type}</td><td>{short(r.to_entity_id)}</td></tr>)}</tbody></table>:<div className="notice"><strong>No governed links yet</strong>Create the first relationship from persisted identities above.</div>}</Panel></div>}

function Access({d,role,reload}:{d:ApiState,role:string,reload:()=>void}) {
  const roles=['administrator','modeler','integration operator','steward','approver','auditor','read only'];
  const [accountName,setAccountName]=useState('scheduled ingestion');
  const [secretName,setSecretName]=useState('supplier_database');
  const [secretValue,setSecretValue]=useState('');
  const [issued,setIssued]=useState('');
  const [msg,setMsg]=useState('');
  const admin=role==='administrator';
  const createAccount=async()=>{try{const created=await request('/service-accounts',role,{method:'POST',body:JSON.stringify({name:accountName,roles:['integration_operator'],scopes:['read','ingest'],expires_in_days:30})});setIssued(created.credential);setMsg('Credential issued once. Copy it now; only its verifier is stored.');reload()}catch(e:any){setMsg(e.message)}};
  const revoke=async(id:string)=>{try{await request(`/service-accounts/${id}/revoke`,role,{method:'POST'});setMsg('Service identity revoked immediately');reload()}catch(e:any){setMsg(e.message)}};
  const createSecret=async()=>{try{await request('/secrets',role,{method:'POST',body:JSON.stringify({name:secretName,provider:'encrypted_local',value:secretValue})});setSecretValue('');setMsg(`Secret reference secret:${secretName} created; plaintext was not returned`);reload()}catch(e:any){setMsg(e.message)}};
  const testSecret=async(id:string)=>{try{const result=await request(`/secrets/${id}/test`,role,{method:'POST'});setMsg(result.available?'Secret resolved without disclosure':'Secret unavailable')}catch(e:any){setMsg(e.message)}};
  return <>
    <div className="grid two">
      <Panel title="Role templates" aside="Backend-enforced">{roles.map(r=><div className="role-row" key={r}><div><strong>{r}</strong><small>{r==='administrator'?'Infrastructure and policy control':r==='auditor'?'Read and audit evidence':'Scoped workspace operations'}</small></div><Badge tone={r.replace(' ','_')===role?'good':'neutral'}>{r.replace(' ','_')===role?'active demo identity':'template'}</Badge></div>)}</Panel>
      <Panel title="Service identities" aside={`${d.serviceAccounts.length} scoped accounts`}><div className="form-stack"><input aria-label="Service account name" value={accountName} onChange={e=>setAccountName(e.target.value)}/><div className="scope-preview"><Badge tone="blue">integration operator</Badge><code>read · ingest · 30 days</code></div><button className="primary" disabled={!admin} title={admin?'Create scoped service identity':'Administrator role required'} onClick={createAccount}>Issue one-time credential</button></div>{issued&&<div className="issued-secret"><small>DISPLAYED ONCE</small><code>{issued}</code><button onClick={()=>navigator.clipboard.writeText(issued)}>Copy credential</button></div>}{d.serviceAccounts.map(a=><div className="role-row" key={a.id}><div><strong>{a.name}</strong><small>{a.scopes.join(' · ')} · expires {fmt(a.expires_at)}</small></div><button disabled={!admin||a.revoked_at} onClick={()=>revoke(a.id)}>{a.revoked_at?'revoked':'Revoke'}</button></div>)}</Panel>
    </div>
    <div className="grid two">
      <Panel title="Secret references" aside="Values never returned"><div className="form-stack"><input aria-label="Secret reference name" value={secretName} onChange={e=>setSecretName(e.target.value)}/><input type="password" autoComplete="new-password" aria-label="Secret value" placeholder="Encrypted with the mounted master key" value={secretValue} onChange={e=>setSecretValue(e.target.value)}/><button className="primary" disabled={!admin||!secretValue} onClick={createSecret}>Store encrypted reference</button></div>{d.secrets.map(s=><div className="role-row" key={s.id}><div><strong>secret:{s.name}</strong><small>{s.provider.replaceAll('_',' ')} · version {s.version}</small></div><button onClick={()=>testSecret(s.id)}>Test access</button></div>)}</Panel>
      <Panel title="Audit trail" aside={d.audit.length?`${d.audit.length} visible entries`:'Restricted for this role'}>{d.audit.length?d.audit.slice(0,10).map(a=><div className="audit-row" key={a.id}><div className="line-dot"/><div><strong>{a.action}</strong><small>{a.actor} · {a.object_type} {short(a.object_id)}</small><code>{short(a.entry_hash)} ← {short(a.previous_hash)}</code></div><span>{fmt(a.created_at)}</span></div>):<div className="locked"><Icon name="access"/><h3>Audit details are restricted</h3><p>The backend denied this field/action path. Counts and error bodies do not reveal audit contents.</p></div>}</Panel>
    </div>
    {msg&&<div className="inline-message">{msg}</div>}
  </>;
}

function Panel({title,aside,children}:{title:string,aside?:any,children:any}){return <section className="panel"><div className="panel-head"><h2>{title}</h2><span>{aside}</span></div><div className="panel-body">{children}</div></section>}
function Empty({title,text}:{title:string,text:string}){return <div className="empty"><span><Diamond size={28}/></span><h3>{title}</h3><p>{text}</p></div>}
