// SPDX-License-Identifier: Apache-2.0
import { useEffect, useMemo, useState } from 'react';
import { ApiState, loadState, request } from './api';
import { navigation as nav } from './navigation';

const labels: Record<string, [string, string]> = {
  overview: ['Operational overview', 'What needs attention across the mastering lane.'],
  models: ['Domain model studio', 'Versioned entities, attributes, identifiers, and operating modes.'],
  sources: ['Source connections', 'Capabilities are declared explicitly; ingestion is read-only by default.'],
  records: ['Source records & quarantine', 'Original contributions remain separate from enterprise identities.'],
  entities: ['Entity explorer', 'Approved records and candidates, with stable enterprise identities.'],
  master: ['Master record', 'The selected value, its source, and the rule that chose it.'],
  matches: ['Match workbench', 'A score is evidence—not proof. Hard contradictions win.'],
  survivorship: ['Survivorship editor', 'Attribute authority is evaluated independently at every change.'],
  inbox: ['Steward inbox', 'Version-bound work with durable decisions and separation of duties.'],
  corrections: ['Merge, split & repair', 'Local identity correction and downstream reconciliation are distinct.'],
  quality: ['Quality & profiling', 'Measured stored state, with scope and sample status disclosed.'],
  simulator: ['Configuration simulator', 'Impact previews bind policy version to a data checkpoint.'],
  operations: ['Publication center', 'At-least-once events with visible delivery and repair state.'],
  relationships: ['Relationship view', 'Typed, effective-dated links over persisted enterprise identities.'],
  access: ['Access, identities & audit', 'Roles shape every API read and action; audit is chained for ordinary roles.'],
};

const fmt = (value?: string) => value ? new Intl.DateTimeFormat('en', {month:'short', day:'numeric', hour:'2-digit', minute:'2-digit'}).format(new Date(value)) : '—';
const short = (value?: string) => value ? value.slice(0, 8) : '—';

function Badge({children, tone='neutral'}:{children:any,tone?:string}) { return <span className={`badge ${tone}`}>{children}</span>; }
function Icon({name}:{name:string}) {
  const paths:Record<string,string>={overview:'M4 4h6v6H4zM14 4h6v10h-6zM4 14h6v6H4zM14 18h6v2h-6z',models:'M5 5h14v4H5zM5 11h6v8H5zM13 11h6v8h-6z',sources:'M7 3v5m10-5v5M5 8h14v5a7 7 0 0 1-14 0zM9 21v-4m6 4v-4',records:'M6 3h9l3 3v15H6zM9 10h6m-6 4h6m-6 4h4',entities:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm8 2a3 3 0 1 0 0-6m-8 7c-4 0-6 2-6 6h12c0-4-2-6-6-6zm8 0c3 0 5 2 5 6h-5',master:'m12 3 2.5 5.2L20 9l-4 4 .9 6L12 16l-4.9 3 .9-6-4-4 5.5-.8z',matches:'m4 7 4-4 4 4M8 3v12a4 4 0 0 0 4 4h8m0 0-4-4m4 4-4 4',survivorship:'M4 6h16M7 6v12m10-12v12M4 18h16m-8-8v4',inbox:'M4 5h16v14H4zM4 14h4l2 2h4l2-2h4',corrections:'M4 12a8 8 0 1 0 3-6M4 4v5h5',quality:'m4 12 5 5L20 6',simulator:'M5 5h14v14H5zM8 15l3-4 3 2 3-5',operations:'M5 4h14v5H5zM5 15h14v5H5zM8 9v6m8-6v6',relationships:'M6 5a3 3 0 1 0 0 6 3 3 0 0 0 0-6zm12 8a3 3 0 1 0 0 6 3 3 0 0 0 0 6zM9 8h5a4 4 0 0 1 4 4v1',access:'M12 3 5 6v5c0 5 3 8 7 10 4-2 7-5 7-10V6z'};
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]||paths.overview}/></svg>;
}

export function App() {
  const currentRoute=()=>{
    const candidate=location.hash.replace(/^#\/?/, '')||'overview';
    return nav.some(([route])=>route===candidate) ? candidate : 'overview';
  };
  const [page,setPage]=useState(currentRoute());
  const [role,setRole]=useState('administrator');
  const [theme,setTheme]=useState(localStorage.getItem('rl-theme')||'dark');
  const [state,setState]=useState<ApiState|null>(null);
  const [error,setError]=useState('');
  const [loading,setLoading]=useState(true);
  const [refresh,setRefresh]=useState(0);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('rl-theme',theme)},[theme]);
  useEffect(()=>{const sync=()=>setPage(currentRoute());window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
  useEffect(()=>{setLoading(true);setError('');loadState(role).then(value=>{setState(value);setError('')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[role,refresh]);
  const go=(id:string)=>{setPage(id);location.hash=id};
  const reload=()=>setRefresh(x=>x+1);
  if(loading&&!state) return <div className="boot"><div className="mark">R</div><span>Preparing the mastering lane…</span></div>;
  return <div className="shell">
    <aside>
      <div className="brand"><div className="mark">R</div><div><strong>recordlane</strong><small>control plane</small></div></div>
      <nav aria-label="Product"><span className="nav-label">Workspace</span>{nav.map(([id,label,index])=><button key={id} aria-label={label} aria-current={page===id?'page':undefined} className={page===id?'active':''} onClick={()=>go(id)}><Icon name={id}/><span>{label}</span><em>{index}</em></button>)}</nav>
      <div className="identity"><div className="avatar">{role[0].toUpperCase()}</div><div><strong>{role.replace('_',' ')}</strong><small>Meridian Works</small></div><span className="online" title="Connected"/></div>
    </aside>
    <main>
      <header><div className="eyebrow"><span>Meridian Works</span><i/>Synthetic workspace</div><div className="actions"><select aria-label="Demo role" value={role} onChange={e=>setRole(e.target.value)}>{['administrator','modeler','integration_operator','steward','approver','auditor','read_only'].map(r=><option key={r}>{r}</option>)}</select><button className="icon-button" aria-label="Toggle theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☼':'◐'}</button><button className="icon-button" aria-label="Refresh" onClick={reload}>↻</button></div></header>
      <section className="title"><div><div className="kicker">{nav.find(n=>n[0]===page)?.[2]} / CONTROL</div><h1>{labels[page]?.[0]}</h1><p>{labels[page]?.[1]}</p></div><div className="status"><span className="pulse"/>Live state · refreshed now</div></section>
      {error&&<div className="notice error"><strong>Could not load workspace</strong>{error}<button onClick={reload}>Retry</button></div>}
      {state&&<Page id={page} data={state} role={role} reload={reload}/>} 
      <footer><span>Recordlane 0.1.0-alpha.1</span><span>Loopback demo · external AI off</span><span>At-least-once publication</span></footer>
    </main>
  </div>;
}

function Page({id,data,role,reload}:{id:string,data:ApiState,role:string,reload:()=>void}) {
  const first=data.entities.find(e=>e.master&&e.approval_state==='approved')||data.entities.find(e=>e.master);
  if(id==='overview') return <Overview d={data}/>;
  if(id==='models') return <Models d={data}/>;
  if(id==='sources') return <Sources d={data}/>;
  if(id==='records') return <Records d={data}/>;
  if(id==='entities') return <Entities d={data}/>;
  if(id==='master') return <Master entity={first}/>;
  if(id==='matches') return <Matches d={data} role={role} reload={reload}/>;
  if(id==='survivorship') return <Survivorship entity={first}/>;
  if(id==='inbox') return <Inbox d={data} role={role} reload={reload}/>;
  if(id==='corrections') return <Corrections d={data} role={role} reload={reload}/>;
  if(id==='quality') return <Quality d={data}/>;
  if(id==='simulator') return <Simulator d={data} role={role} reload={reload}/>;
  if(id==='operations') return <Operations d={data} role={role} reload={reload}/>;
  if(id==='relationships') return <Relationships d={data}/>;
  return <Access d={data} role={role}/>;
}

function Overview({d}:{d:ApiState}) {const c=d.overview.counts;return <>
  <div className="metric-grid"><Metric value={c.source_records} label="Source contributions" note="Across 3 local sources"/><Metric value={c.open_reviews} label="Open decisions" note="Version-bound queue" tone="amber"/><Metric value={c.quarantined} label="Quality exceptions" note="Preserved for repair" tone="red"/><Metric value={c.outbox_pending} label="Pending deliveries" note="Consumer reconciliation" tone="blue"/></div>
  <div className="grid two"><Panel title="Attention lane" aside="Ordered by consequence"><div className="attention"><Attention tone="red" n={c.quarantined} title="Record held in quarantine" text="Invalid jurisdiction, identifier, and lifecycle values."/><Attention tone="amber" n={d.tasks.filter(t=>t.kind==='duplicate_match'&&t.status==='open').length} title="Identity decisions waiting" text="Similarity evidence requires steward judgment."/><Attention tone="blue" n={c.outbox_pending} title="Approved changes awaiting relay" text="No downstream consistency is implied until reconciled."/></div></Panel><Panel title="Source freshness" aside="Measured from persisted checkpoints"><table><thead><tr><th>Source</th><th>Mode</th><th>Last observed</th><th>State</th></tr></thead><tbody>{d.sources.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{s.kind}</td><td>{fmt(s.last_ingested_at)}</td><td><Badge tone="good">{s.status}</Badge></td></tr>)}</tbody></table></Panel></div>
  <Panel title="Mastering flow" aside="Current workspace"><div className="flow"><Flow n="01" title="Collect" text={`${c.source_records} source records`}/><Flow n="02" title="Resolve" text={`${d.entities.length} stable identities`}/><Flow n="03" title="Govern" text={`${c.open_reviews} open decisions`}/><Flow n="04" title="Publish" text={`${c.mastered_entities} approved masters`}/></div></Panel>
  </>}
function Metric({value,label,note,tone='lime'}:{value:any,label:string,note:string,tone?:string}){return <div className={`metric ${tone}`}><div className="metric-top"><span>{label}</span><i/></div><strong>{String(value).padStart(2,'0')}</strong><small>{note}</small></div>}
function Attention({tone,n,title,text}:{tone:string,n:number,title:string,text:string}){return <div className="attention-row"><span className={`count ${tone}`}>{n}</span><div><strong>{title}</strong><p>{text}</p></div><span>→</span></div>}
function Flow({n,title,text}:{n:string,title:string,text:string}){return <div className="flow-step"><em>{n}</em><strong>{title}</strong><span>{text}</span></div>}

function Models({d}:{d:ApiState}){const selected=d.domains[0];return <div className="grid sidebar-grid"><Panel title="Domains" aside={`${d.domains.length} published`}>{d.domains.map(x=><div className="list-row selected" key={x.id}><div className="square">{x.name[0]}</div><div><strong>{x.name}</strong><small>{x.mode} · v{x.schema_version}</small></div><Badge tone="good">{x.status}</Badge></div>)}</Panel><Panel title={selected?.name||'Domain'} aside="Canonical model"><div className="model-head"><div><Badge tone="purple">{selected?.mode}</Badge><h2>{selected?.definition?.entity}</h2><p>Source systems retain operational ownership; Recordlane governs identity and approved attributes.</p></div><button disabled title="Editing requires a modeler role and draft version">Create draft</button></div><table><thead><tr><th>Attribute</th><th>Type</th><th>Required</th><th>Controls</th></tr></thead><tbody>{selected?.definition?.attributes?.map((a:any)=><tr key={a.key}><td><strong>{a.name}</strong><code>{a.key}</code></td><td>{a.type}</td><td>{a.required?'Yes':'No'}</td><td>{a.pattern?'Pattern':a.allowed_values?'Allowed values':'Standard'}</td></tr>)}</tbody></table></Panel></div>}

function Sources({d}:{d:ApiState}){return <><div className="source-grid">{d.sources.map((s,i)=><div className="source-card" key={s.id}><div className="source-num">0{i+1}</div><Badge tone="good">{s.status}</Badge><h3>{s.name}</h3><p>{s.kind.toUpperCase()} · priority {s.priority}</p><dl><dt>Full read</dt><dd>{String(s.capabilities.full_read)}</dd><dt>Incremental</dt><dd>{s.capabilities.incremental}</dd><dt>Deletion</dt><dd>{s.capabilities.deletions}</dd><dt>Validation</dt><dd>{s.capabilities.validation}</dd></dl><button disabled title="Credentials are read-only in the public demo">Configure</button></div>)}</div><div className="notice"><strong>Capability honesty</strong>These local connectors were exercised in the demo profile. Vendor recipes and emulators never appear here as live-validated connections.</div></>}

function Records({d}:{d:ApiState}){const [filter,setFilter]=useState('all');const rows=filter==='all'?d.records:d.records.filter(r=>r.state===filter);return <Panel title="Contribution ledger" aside={`${rows.length} of ${d.records.length} records`}><div className="toolbar"><div className="segmented">{['all','valid','quarantine'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><input placeholder="Filter current page" aria-label="Filter records"/></div><table><thead><tr><th>Source key</th><th>Original name</th><th>Identifier</th><th>Observed</th><th>State</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><code>{r.local_id}</code><small>v{r.source_version}</small></td><td><strong dir="auto">{r.original.name}</strong>{r.quality_errors?.[0]&&<small className="danger">{r.quality_errors[0].message}</small>}</td><td>{r.original.tax_id||'—'}</td><td>{fmt(r.observed_at)}</td><td><Badge tone={r.state==='valid'?'good':'red'}>{r.state}</Badge></td></tr>)}</tbody></table></Panel>}

function Entities({d}:{d:ApiState}){return <Panel title="Enterprise identities" aside="Candidates are labeled"><div className="toolbar"><input placeholder="Search approved values"/><button>Saved views</button><button>Export visible</button></div><table><thead><tr><th>Stable identity</th><th>Selected name</th><th>Jurisdiction</th><th>Version</th><th>State</th></tr></thead><tbody>{d.entities.map(e=><tr key={e.id}><td><code>{e.stable_key}</code></td><td><strong dir="auto">{e.master?.values?.name||'Awaiting master'}</strong></td><td>{e.master?.values?.country||'—'}</td><td>v{e.master?.version||e.version}</td><td><Badge tone={e.approval_state==='approved'?'good':'amber'}>{e.approval_state}</Badge></td></tr>)}</tbody></table></Panel>}

function Master({entity}:{entity:any}){const values=entity?.master?.values||{},prov=entity?.master?.provenance||{};return <div className="grid master-grid"><Panel title={values.name||'No selected entity'} aside={entity?.stable_key}><div className="record-hero"><div className="monogram">{values.name?.[0]||'R'}</div><div><Badge tone={entity?.approval_state==='approved'?'good':'amber'}>{entity?.approval_state}</Badge><h2 dir="auto">{values.name}</h2><p>{values.country} · {values.tax_id}</p></div></div><div className="attribute-list">{Object.entries(values).map(([k,v])=><div className="attribute" key={k}><span>{k.replace('_',' ')}</span><strong dir="auto">{String(v)}</strong><small>{prov[k]?.source||'Source pending'} · {prov[k]?.verification||'unverified'}</small></div>)}</div></Panel><Panel title="Selection explanation" aside={`Master v${entity?.master?.version||'—'}`}>{Object.entries(prov).map(([k,p]:any)=><div className="provenance" key={k}><div className="line-dot"/><div><strong>{k.replace('_',' ')}</strong><p>Selected from <b>{p.source}</b> by {p.rule.replaceAll('_',' ')}.</p><div><Badge tone={p.verification==='verified'?'good':'neutral'}>{p.verification}</Badge><code>source v{p.source_version}</code><span>{p.alternatives} competing</span></div></div></div>)}</Panel></div>}

function Matches({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const task=d.tasks.find(t=>t.kind==='duplicate_match'&&t.status==='open');const [message,setMessage]=useState('');const act=async(decision:string)=>{if(!task)return;try{await request(`/review-tasks/${task.id}/decision`,role,{method:'POST',body:JSON.stringify({decision,reason:decision==='link'?'Evidence reviewed; records represent one supplier':'Identifiers remain ambiguous; keep separate'})});setMessage('Decision persisted');reload()}catch(e:any){setMessage(e.message)}};if(!task)return <Empty title="No match reviews are open" text="New ambiguous evidence will enter this workbench."/>;const p=task.payload;return <div className="grid match-grid"><Panel title="Candidate pair" aside={`Policy ${p.policy_version}`}><div className="score"><strong>{Math.round(p.score*100)}</strong><span>/ 100 weighted score</span><Badge tone="amber">human review</Badge></div><div className="compare"><div><small>NEW CONTRIBUTION</small><h3>{short(p.left_record_id)}</h3></div><div className="versus">↔</div><div><small>EXISTING CONTRIBUTION</small><h3>{short(p.right_record_id)}</h3></div></div><div className="decision-bar"><button onClick={()=>act('keep_separate')}>Keep separate</button><button className="primary" onClick={()=>act('link')}>Link identities</button></div>{message&&<div className="inline-message">{message}</div>}</Panel><Panel title="Evidence ledger" aside="No calibrated probability claim">{p.evidence.map((e:any)=><div className="evidence" key={e.field}><div><strong>{e.field}</strong><small>{e.comparator} · weight {e.weight}</small></div><div className="bar"><i style={{width:`${e.score*100}%`}}/></div><b>{Math.round(e.score*100)}</b></div>)}{p.contradictions?.length?<div className="notice error">Hard contradiction prevents linking.</div>:<div className="notice"><strong>No hard contradiction</strong>Similarity still requires stewardship at this threshold.</div>}</Panel></div>}

function Survivorship({entity}:{entity:any}){const p=entity?.master?.provenance||{};return <Panel title="Attribute authority" aside="Deterministic tie-breaking"><table><thead><tr><th>Attribute</th><th>Current authority</th><th>Verification</th><th>Fallbacks</th><th>Re-evaluation</th></tr></thead><tbody>{Object.entries(p).map(([k,v]:any)=><tr key={k}><td><strong>{k.replace('_',' ')}</strong></td><td>{v.source}</td><td><Badge tone={v.verification==='verified'?'good':'neutral'}>{v.verification}</Badge></td><td>{v.alternatives}</td><td>On contribution or policy change</td></tr>)}</tbody></table><div className="notice"><strong>Sensitive identifier guard</strong>A newer unverified spreadsheet value cannot replace a verified legal identifier under this policy.</div></Panel>}

function Inbox({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const [msg,setMsg]=useState('');const open=d.tasks.filter(t=>t.status==='open');const decide=async(t:any)=>{try{await request(`/review-tasks/${t.id}/decision`,role,{method:'POST',body:JSON.stringify({decision:'approve',reason:'Reviewed exact version and supporting provenance'})});setMsg('Approval committed with its publication event');reload()}catch(e:any){setMsg(e.message)}};return <div className="grid sidebar-grid"><Panel title="Queue" aside={`${open.length} open`}>{open.map(t=><button className="task-row" key={t.id}><span className={`task-kind ${t.priority}`}/><div><strong>{t.kind.replace('_',' ')}</strong><small>{t.sensitive?'Sensitive · independent approval':'Standard review'} · due {fmt(t.due_at)}</small></div><code>{short(t.id)}</code></button>)}</Panel><Panel title="Decision detail" aside="Bound to exact version">{open[0]?<><div className="decision-summary"><Badge tone={open[0].sensitive?'red':'neutral'}>{open[0].sensitive?'sensitive':'standard'}</Badge><h2>{open[0].kind.replace('_',' ')}</h2><p>Entity version {open[0].bound_entity_version} · workflow version {open[0].workflow_version}</p></div><pre>{JSON.stringify(open[0].payload.values||open[0].payload.evidence||{},null,2)}</pre><div className="decision-bar"><button>Reject</button><button className="primary" onClick={()=>decide(open[0])}>Approve exact version</button></div>{msg&&<div className="inline-message">{msg}</div>}</>:<Empty title="Queue cleared" text="There is no open item for this filter."/>}</Panel></div>}

function Corrections({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const merged=d.entities.filter(e=>e.status==='merged');const candidates=d.entities.filter(e=>e.status==='active').slice(0,2);const [preview,setPreview]=useState<any>(null);const [msg,setMsg]=useState('');const run=async(commit=false)=>{setMsg('');try{const result=await request(commit?'/merges':'/merges/preview',role,{method:'POST',body:JSON.stringify({entity_ids:candidates.map(e=>e.id),reason:'Operator-reviewed duplicate correction'})});if(commit){setMsg(`Merge proposal ${short(result.id)} opened for independent approval`);reload()}else setPreview(result)}catch(e:any){setMsg(e.message)}};return <><div className="metric-grid three"><Metric value={merged.length} label="Merged aliases" note="Stable references preserved"/><Metric value={d.tasks.filter(t=>t.kind==='merge'&&t.status==='open').length} label="Ambiguous repairs" note="Require operator judgment" tone="amber"/><Metric value={d.overview.counts.outbox_pending} label="Consumer checks" note="Not called rolled back" tone="blue"/></div><Panel title="Correction ledger" aside="Local correction ≠ downstream rollback">{candidates.length===2?<><div className="compare"><div><small>PRIMARY CANDIDATE</small><h3>{candidates[0].master?.values?.name||candidates[0].stable_key}</h3><code>{candidates[0].stable_key}</code></div><div className="versus">+</div><div><small>ALIAS CANDIDATE</small><h3>{candidates[1].master?.values?.name||candidates[1].stable_key}</h3><code>{candidates[1].stable_key}</code></div></div>{preview&&<div className="impact"><div><strong>{preview.source_records}</strong><span>source records preserved</span></div><div><strong>{preview.relationships}</strong><span>relationships affected</span></div></div>}<div className="decision-bar"><button onClick={()=>run(false)}>Preview impact</button><button className="primary" onClick={()=>run(true)}>Propose merge</button></div></>:<Empty title="No correction candidates" text="At least two active identities are required for a governed preview."/>}{msg&&<div className="inline-message">{msg}</div>}</Panel></>}

function Quality({d}:{d:ApiState}){const bad=d.records.filter(r=>r.state==='quarantine');const completeness=Math.round(100*d.records.filter(r=>r.original.name&&r.original.country).length/d.records.length);return <><div className="metric-grid three"><Metric value={`${completeness}%`} label="Required completeness" note={`Full scope · n=${d.records.length}`}/><Metric value={new Set(d.records.map(r=>r.original.tax_id).filter(Boolean)).size} label="Unique identifiers" note="Namespace-aware distinct" tone="blue"/><Metric value={bad.length} label="Invalid records" note="Measured from stored state" tone="red"/></div><Panel title="Actionable exceptions" aside="Full population · measured now"><table><thead><tr><th>Record</th><th>Field</th><th>Rule</th><th>Recovery</th></tr></thead><tbody>{bad.flatMap(r=>r.quality_errors.map((e:any)=><tr key={`${r.id}-${e.attribute}`}><td><code>{r.local_id}</code></td><td>{e.attribute}</td><td><Badge tone="red">{e.code}</Badge> {e.message}</td><td>Repair source value, then reprocess</td></tr>))}</tbody></table></Panel></>}

function Simulator({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const s=d.simulations[0];const [msg,setMsg]=useState('');const run=async()=>{try{await request(`/configurations/${d.configs[0].id}/simulate`,role,{method:'POST'});setMsg('New checkpoint-bound simulation persisted');reload()}catch(e:any){setMsg(e.message)}};return <div className="grid two"><Panel title="Policy diff" aside={`Draft v${d.configs[0]?.version||'—'}`}><div className="diff"><span>- review threshold <b>0.62</b></span><span>+ review threshold <b>0.58</b></span><span>+ tax_id <b>verified only</b></span></div><button className="primary" onClick={run}>Recompute impact</button>{msg&&<div className="inline-message">{msg}</div>}</Panel><Panel title="Measured impact" aside={`Data checkpoint ${s?.data_checkpoint||'—'}`}>{s&&<div className="impact">{Object.entries(s.result).map(([k,v])=><div key={k}><strong>{String(v).padStart(2,'0')}</strong><span>{k.replaceAll('_',' ')}</span></div>)}</div>}<div className={`notice ${s?.stale?'error':''}`}><strong>{s?.stale?'Preview expired':'Preview is current'}</strong>{s?.stale?'Source state changed; recompute before approval.':'Bound configuration and data checkpoint still match.'}</div></Panel></div>}

function Operations({d,role,reload}:{d:ApiState,role:string,reload:()=>void}){const [msg,setMsg]=useState('');const relay=async()=>{try{const result=await request('/operations/relay',role,{method:'POST'});setMsg(`${result.delivered} delivered, ${result.failed} failed, ${result.processed} processed`);reload()}catch(e:any){setMsg(e.message)}};return <Panel title="Transactional outbox" aside={d.operations.delivery_semantics}><div className="toolbar"><button className="primary" onClick={relay}>Relay pending events</button></div><table><thead><tr><th>Event</th><th>Entity / version</th><th>Occurred</th><th>Attempts</th><th>Delivery</th></tr></thead><tbody>{d.operations.outbox.map((e:any)=><tr key={e.id}><td><strong>{e.event_type}</strong><code>{short(e.id)}</code></td><td>{short(e.entity_id)} · v{e.entity_version}</td><td>{fmt(e.occurred_at)}</td><td>{e.attempts}</td><td><Badge tone={e.status==='delivered'?'good':'amber'}>{e.status}</Badge></td></tr>)}</tbody></table>{msg&&<div className="inline-message">{msg}</div>}<div className="notice"><strong>Ordering and consistency</strong>Ordering is per entity. A remote 2xx means accepted, not verified business consistency.</div></Panel>}

function Relationships({d}:{d:ApiState}){const nodes=d.entities.slice(0,4);return <div className="grid two"><Panel title="Identity graph" aside="Persisted nodes only"><div className="graph" role="img" aria-label="Table-equivalent relationship view"><svg viewBox="0 0 600 340"><line x1="150" y1="100" x2="440" y2="170"/><line x1="150" y1="100" x2="190" y2="270"/>{nodes.map((n,i)=>{const pos=[[150,100],[440,170],[190,270],[460,285]][i];return <g key={n.id} transform={`translate(${pos[0]},${pos[1]})`}><circle r="44"/><text textAnchor="middle" y="5">{n.master?.values?.name?.slice(0,10)||short(n.id)}</text></g>})}</svg></div></Panel><Panel title="Accessible relationship table" aside={`${d.relationships.length} effective links`}>{d.relationships.length?<table><tbody>{d.relationships.map(r=><tr key={r.id}><td>{short(r.from_entity_id)}</td><td>{r.type}</td><td>{short(r.to_entity_id)}</td></tr>)}</tbody></table>:<Empty title="No governed links yet" text="Unconnected identity nodes remain real entities, not decorative graph data."/>}</Panel></div>}

function Access({d,role}:{d:ApiState,role:string}){const roles=['administrator','modeler','integration operator','steward','approver','auditor','read only'];return <div className="grid two"><Panel title="Role templates" aside="Editable in production">{roles.map(r=><div className="role-row" key={r}><div><strong>{r}</strong><small>{r==='administrator'?'Infrastructure and policy control':r==='auditor'?'Read and audit evidence':'Scoped workspace operations'}</small></div><Badge tone={r.replace(' ','_')===role?'good':'neutral'}>{r.replace(' ','_')===role?'active demo identity':'template'}</Badge></div>)}</Panel><Panel title="Audit trail" aside={d.audit.length?`${d.audit.length} visible entries`:'Restricted for this role'}>{d.audit.length?d.audit.slice(0,10).map(a=><div className="audit-row" key={a.id}><div className="line-dot"/><div><strong>{a.action}</strong><small>{a.actor} · {a.object_type} {short(a.object_id)}</small><code>{short(a.entry_hash)} ← {short(a.previous_hash)}</code></div><span>{fmt(a.created_at)}</span></div>):<div className="locked"><Icon name="access"/><h3>Audit details are restricted</h3><p>The backend denied this field/action path. Counts and error bodies do not reveal audit contents.</p></div>}</Panel></div>}

function Panel({title,aside,children}:{title:string,aside?:any,children:any}){return <section className="panel"><div className="panel-head"><h2>{title}</h2><span>{aside}</span></div><div className="panel-body">{children}</div></section>}
function Empty({title,text}:{title:string,text:string}){return <div className="empty"><span>◇</span><h3>{title}</h3><p>{text}</p></div>}
